### ISSUE TITLE
apiurl in key

### ISSUE THREAD

**Issue by gregorkrz** [gasperTheGhost/covid-solver-unix#2]
Bi se dalo dobiti vrednosti spremenljivk apiurl in key, ki so vdelane v prevedeno verzijo covid-solver.sh? Potrebujem namreč verzijo za arhitekturo ARM

**Comment by gasperTheGhost** [comment]
Lahko se zmenimo, najlažje preko discorda gasperTheGhost#6161 ali https://discord.gg/QJhhdH
API ključi načeloma niso za javnost
